#!/usr/bin/env python3

import os
import sys
import shutil
import argparse
import subprocess

DIR              = os.path.dirname(__file__)
PHOBIUS_BIN      = os.path.join(DIR, 'dependencies/phobius/phobius.pl')

def run_phobius(INPUT, OUTPUT):
    results = subprocess.check_output([PHOBIUS_BIN, '-short', INPUT])
    results = results.decode("utf-8")
    results = results.splitlines()
    # The first line is:
    #    SEQENCE ID                     TM SP PREDICTION
    results = results[1:]

    tbl_file = OUTPUT + ".out"
    with open(tbl_file, "w") as output_F:
        output_F.write("ID\tTM\tSP\tPREDICTION\n")
        for line in results:
            items = line.split()
            output_F.write("\t".join(items) + "\n")

def convert_gff(OUTPUT):
    tbl_file = OUTPUT + ".out"
    gff_file = OUTPUT + ".gff"

    input = open(tbl_file, "r")
    output = open(gff_file, "w")

    output.write("##gff-version 3\n")

    lines = input.readlines()
    lines = lines[1:] # Remove header
    for line in lines:
        line = line.rstrip()
        words = line.split()

        SEQID      = words[0]
        SOURCE     = "phobius"
        TYPE       = "."
        FROM       = "."
        TO         = "."
        SCORE      = "."
        STRAND     = "."
        PHASE      = "."

        ADDITIONAL = [
            "TM={}".format(words[1]),
            "SP={}".format(words[2]),
            "PREDICTION={}".format(words[3])
        ]
        ADDITIONAL = ";".join(ADDITIONAL)
        string_gff = "\t".join([SEQID, SOURCE, TYPE, FROM, TO, SCORE, STRAND, PHASE, ADDITIONAL])
        output.write(string_gff + "\n")

def parse_args():
    parser = argparse.ArgumentParser(description='Run phobius program')
    parser.add_argument('-i', '--input', required=True,
                        help='Path of a fasta file containing protein sequence')
    parser.add_argument('-o', '--output', required=True,
                        help='Prefix of output file')
    args = parser.parse_args()
    return args

def main():
    ## Parse args
    args = parse_args()
    INPUT = args.input
    OUTPUT = args.output

    ## Run phobius program
    run_phobius(INPUT, OUTPUT)
    convert_gff(OUTPUT)

if __name__ == "__main__":
    main()
